apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-workloads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-workloads
  template:
    metadata:
      labels:
        app: k8s-workloads
    spec:
      serviceAccountName: k8s-workloads-sa
      containers:
      - name: k8s-workloads
        image: registry.digitalocean.com/hun7er/k8s-workloads:0.0.19
        ports:
        - containerPort: 32443
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: regcred
