apiVersion: v1
kind: Service
metadata:
  name: k8s-workloads
spec:
  type: NodePort
  selector:
    app: k8s-workloads
  ports:
    - protocol: TCP
      port: 32443
      targetPort: 32443
      nodePort: 32443
